-
  branches:
    only:
      - master
      - develop
  configuration: Release
  platform: Any CPU
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  install:
    - choco install gitversion.portable -y

  before_build:
    - ps: nuget restore
    - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  build:
    project: AsyncSuffix.sln
    verbosity: minimal
  test: off
- 
  branches:
    only:
      - feature/conditional-build
  configuration: Debug
  platform: Any CPU
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  install:
    - choco install gitversion.portable -y

  before_build:
    - ps: nuget restore
    - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  build:
    project: AsyncSuffix.sln
    verbosity: minimal
  test: off
  after_build:
    - nuget pack AsyncSuffix/AsyncSuffix.nuspec